In [68]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [69]:
df_tabela_ligantes = pd.read_excel("df_tabela_ligantes.xlsx")
display(df_tabela_ligantes)

    Rótulo Hora Início  Hora Fim  Número Médio Ligantes
0        1    18:15:00  18:30:00                   2071
1        2    18:30:00  18:45:00                   2002
2        3    18:45:00  19:00:00                   1982
3        4    19:00:00  19:15:00                   1835
4        5    19:15:00  19:30:00                   1540
..     ...         ...       ...                    ...
91      92    17:00:00  17:15:00                   3143
92      93    17:15:00  17:30:00                   3247
93      94    17:30:00  17:45:00                   3009
94      95    17:45:00  18:00:00                   2747
95      96    18:00:00  18:15:00                   2297

[96 rows x 4 columns]

In [70]:
df_duracoes = pd.read_excel("df_duracoes.xlsx")
display(df_duracoes)

,Duração Conexão,Número Ligantes,Percentagem Relativa,Percentagem Acumulada
0,0,0,0.000,0.000
1,5,870,0.087,0.087
2,10,2210,0.221,0.308
3,15,2940,0.294,0.602
4,20,1710,0.171,0.773
5,25,1360,0.136,0.909
6,30,590,0.059,0.968
7,35,250,0.025,0.993
8,40,70,0.007,1.000

In [71]:
coefs = np.polyfit(x = df_duracoes["Percentagem Acumulada"], y = df_duracoes["Duração Conexão"], deg = 5 )

ft = np.poly1d(coefs, variable = "p") #transforma isso numa funcao matematica
print(ft)

       5        4        3         2
725.3 p - 1678 p + 1413 p - 523.8 p + 101 p - 0.2063

In [72]:
#para p = 0 => t = -0.20s
print(ft(0))

-0.20625385912792726

In [73]:
#para p = 1 => t = 37.63s
print(ft(1))

37.631298535355725

In [74]:
qtd_ligantes = df_tabela_ligantes.loc[0, "Número Médio Ligantes"]
print(qtd_ligantes)

2071

In [75]:
np.random.seed(40)
momentos_ligacoes = np.random.randint(low = 0, high = 900, size = qtd_ligantes)
momentos_ligacoes.sort()
print(momentos_ligacoes)
#isso significa que a primeira ligacao aconteceu em 18:15:02
#segunda ligacao 18:15:02
#ligacao 899 18:29:59
#ligacao 900 18:30:00

#sempre usando o primeiro tempo ta tabela como base pro inico do tempo

[  2   2   3 ... 898 899 899]

In [76]:
atendentes: list[dict] = [] #essa notacao esquisita e uma dica da tipagem tipo julia
#talvez seja melhor trocar a estrutura pra um pd ou quem sabe uma matriz

In [77]:
momento_ligacao = momentos_ligacoes[0]
print(momento_ligacao)

2

In [78]:
np.random.seed(43)
duracao = ft(np.random.random())
print(duracao)

6.354580517497224

In [80]:
np.random.seed(1)
coluna_nan = []
espera = 10
for qtd_ligantes in df_tabela_ligantes["Número Médio Ligantes"]:
    #print(qtd_ligantes)
    momentos_ligacoes = np.random.randint(low = 0, high = 900, size = qtd_ligantes)
    momentos_ligacoes.sort()
    atendentes = []
    for momento_ligacao in momentos_ligacoes:
        #print(momento_ligacao, end = " ")
    #print("-" * 30)
        duracao = ft(np.random.random())

        if len(atendentes) == 0:
            atendentes.append({"inicio" : momento_ligacao,
                              "final"  : momento_ligacao + duracao})
            
            continue

        for atendente in atendentes:
            ocupado = atendente["final"] > momento_ligacao + espera
            if not ocupado:
                
                if momento_ligacao > atendente["final"]:
                    atendente["inicio"] = momento_ligacao
                    atendente["final"] = momento_ligacao + duracao
                else:
                    atendente["inicio"] = atendente["final"]
                    atendente["final"] = atendente["inicio"] + duracao
                break
        else:
            atendentes.append({"inicio" : momento_ligacao,
                              "final"  : momento_ligacao + duracao})  
            
    nan = len(atendentes)
    coluna_nan.append(nan)
print(coluna_nan)

[44, 43, 44, 41, 34, 33, 35, 32, 33, 32, 35, 30, 28, 25, 23, 27, 24, 20, 21, 22, 15, 15, 16, 17, 7, 6, 7, 6, 4, 6, 4, 4, 5, 5, 4, 4, 3, 3, 3, 3, 3, 3, 5, 3, 3, 3, 3, 5, 7, 4, 5, 16, 14, 20, 17, 34, 32, 35, 37, 54, 55, 53, 56, 65, 63, 63, 65, 61, 54, 59, 57, 51, 53, 55, 50, 54, 62, 59, 61, 61, 59, 59, 57, 59, 59, 64, 56, 60, 58, 59, 61, 58, 65, 63, 55, 51]